export interface Item {
  nameid: number
  name: string
  jname: string
  value_buy: number
  value_sell: number
  type: number
  subtype: number
  sex: number
  equip: number
  weight: number
  atk: number
  def: number
  range: number
  slot: number
  view_sprite: number
  elv: number
  wlv: number
  view_id: number
  matk: number
  elvmax: number
  delay: number
  flag_trade: number
  flag_refine: number
  flag_buystore: number
  id: number
  account_id: number
  char_id: number
  char_name: string
  shop_name: string
  mapname: string
  map_x: number
  map_y: number
  job: number
  clone_id: number
  idx: number
  price: number
  identify: number
  refine: number
  attribute: number
  unique_id: number
  bonus_time: number
  data: Record<string, any>
  opts: any[]
  cards: any[]
  cards_sulfix: any[]
  amount: number
  is_sub: boolean
}
